:PROPERTIES:
:ID:       b7697048-9cd2-4019-866d-814b0aa31913
:END:
#+title: OU:M208:Unit-A2:Complex Numbers
#+filetags: OU M208 Mathematics Complex-Numbers

See [[id:e5ef161f-83e0-49d8-a4b9-e02eb660efe8][OU:M208:Unit-A2:Complex Numbers:What is a Complex Number?]] for an introduction to the concept of complex numbers.

See [[id:30aee997-9cab-4d93-b03f-6cea2a94df7b][OU:M208:Unit-A2:Complex Numbers:The Complex Plane]] to understand how complex numbers can map to points in a plane.

See [[id:6274d52c-220c-4342-afe2-01b869ea0609][OU:M208:Unit-A2:Complex Numbers:Arithmetic of Complex Numbers]] for some basic operations that can be applied to two complex numbers.

See [[id:e632b886-54fd-446e-9f73-8122f136206d][OU:M208:Unit-A2:Complex Numbers:Complex Conjugate]] for an introduction to the complex conjugate.

See [[id:c5b4589b-8871-43cc-b88b-b9d6e5d025b8][OU:M208:Unit-A2:Complex Numbers:Modulus of a Complex Number]] to learn how to take the modulus of a complex number and its relationship with the complex conjugate.

See [[id:dce6f3cd-8223-4c84-941b-43d868a67156][OU:M208:Unit-A2:Complex Numbers:Division of a Complex Number]] to see how to find the reciprocal of a complex number.

See [[id:2646d013-1152-4176-8b6e-f60b2be27f0d][OU:M208:Unit-A2:Complex Numbers:Arithmetic Properties of Complex Numbers]] for the properties of addition and multiplication for complex numbers.
