:PROPERTIES:
:ID:       1e516c7b-6686-4283-abbd-e0859d029b0c
:END:
#+title: OU:M208:Unit-A3:Mathematical Statements:Direct Proof
#+filetags: OU M208 Mathematics Proofs Statements Direct-Proof

+ Proof By Exhaustion :: Proving a staement by enumerating all possibilities

  #+begin_example
  If n is an odd number between 0 and 10, then n squared is also odd

  The odd numbers between 0 and 10 are 1, 3, 5, 7 and 9.
  Their squares are 1, 9, 25, 49 and 81, respectively.
  As those squares are all odd numbers, the statement holds.
  #+end_example

Most of the time we cannot so easily enumerate all the possibilities of a statement, requiring us a more general proof.

There are many ways to make such a proof. For an example of one see [[id:54a763f3-464b-4fe9-acf2-d57f10ab0fc2][OU:M208:Theorems:A12:Geometric Series Identity]].

------

See [[id:454ae869-8636-4f9d-a293-ef958408f918][OU:M208:Unit-A3:Mathematical Statements:Direct Proof:Proving Implications]] to understand how to prove an implication \(P \implies Q\).

See [[id:8f4cf6f6-e56a-48d7-813e-9158ee8c982a][OU:M208:Unit-A3:Direct Proof:Proving Equivalences]]  to understand how to prove an equivalence \(P \iff Q\).

See [[id:5d3e062b-c447-4cc0-bce8-3d8c63ac3274][OU:M208:Unit-A3:Direct Proof:Proving Existential and Universal Statement]] to understand how to prove existential and universal statements.

See [[id:1ae75249-51e2-458a-a6c9-5849b297abdd][OU:M208:Unit-A3:Direct Proof:Counterexamples]] to understand how to prove that a universal statement is false.

See [[id:e6f5dd9b-091e-4cfe-b351-4241b050b9a8][OU:M208:Unit-A3:Direct Proof:Proof By Induction]] to learn about the import method of induction to build general proofs.
